#Application Property
app:
  demoText: City Temperature
  
#Log file path
logging:
  file: /tmp/spring-boot-mvc.log
  level:
      day4.cityTemp.assignment: DEBUG
      org.springframework: INFO
    
     
#Server property 
server:
  port: 8080
  contextPath: /cityTempJmsApp
        